package com.pospi.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pospi.dto.GoodsDto;
import com.pospi.dto.Tablebeen;

import com.pospi.greendao.GoodsDtoDao;
import com.pospi.greendao.TablebeenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsDtoDaoConfig;
    private final DaoConfig tablebeenDaoConfig;

    private final GoodsDtoDao goodsDtoDao;
    private final TablebeenDao tablebeenDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsDtoDaoConfig = daoConfigMap.get(GoodsDtoDao.class).clone();
        goodsDtoDaoConfig.initIdentityScope(type);

        tablebeenDaoConfig = daoConfigMap.get(TablebeenDao.class).clone();
        tablebeenDaoConfig.initIdentityScope(type);

        goodsDtoDao = new GoodsDtoDao(goodsDtoDaoConfig, this);
        tablebeenDao = new TablebeenDao(tablebeenDaoConfig, this);

        registerDao(GoodsDto.class, goodsDtoDao);
        registerDao(Tablebeen.class, tablebeenDao);
    }
    
    public void clear() {
        goodsDtoDaoConfig.clearIdentityScope();
        tablebeenDaoConfig.clearIdentityScope();
    }

    public GoodsDtoDao getGoodsDtoDao() {
        return goodsDtoDao;
    }

    public TablebeenDao getTablebeenDao() {
        return tablebeenDao;
    }

}
