package com.pospi.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.pospi.dto.GoodsDto;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GOODS_DTO".
*/
public class GoodsDtoDao extends AbstractDao<GoodsDto, Long> {

    public static final String TABLENAME = "GOODS_DTO";

    /**
     * Properties of entity GoodsDto.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Sid = new Property(1, String.class, "Sid", false, "SID");
        public final static Property UId = new Property(2, String.class, "UId", false, "UID");
        public final static Property Category_sid = new Property(3, String.class, "category_sid", false, "CATEGORY_SID");
        public final static Property ColorCode = new Property(4, String.class, "colorCode", false, "COLOR_CODE");
        public final static Property Group_sid = new Property(5, String.class, "group_sid", false, "GROUP_SID");
        public final static Property Image = new Property(6, String.class, "image", false, "IMAGE");
        public final static Property Name = new Property(7, String.class, "name", false, "NAME");
        public final static Property Price = new Property(8, double.class, "price", false, "PRICE");
        public final static Property CostPrice = new Property(9, double.class, "CostPrice", false, "COST_PRICE");
        public final static Property Unit = new Property(10, String.class, "unit", false, "UNIT");
        public final static Property MainPrinterSid = new Property(11, String.class, "mainPrinterSid", false, "MAIN_PRINTER_SID");
        public final static Property BackPrinterSid = new Property(12, String.class, "backPrinterSid", false, "BACK_PRINTER_SID");
        public final static Property Code = new Property(13, String.class, "Code", false, "CODE");
        public final static Property CreateTime = new Property(14, String.class, "createTime", false, "CREATE_TIME");
        public final static Property OrderBy = new Property(15, int.class, "orderBy", false, "ORDER_BY");
        public final static Property IsHide = new Property(16, boolean.class, "isHide", false, "IS_HIDE");
        public final static Property ProPrice = new Property(17, double.class, "proPrice", false, "PRO_PRICE");
        public final static Property ProType = new Property(18, String.class, "proType", false, "PRO_TYPE");
        public final static Property ProDiscout = new Property(19, double.class, "proDiscout", false, "PRO_DISCOUT");
        public final static Property OldPrice = new Property(20, double.class, "oldPrice", false, "OLD_PRICE");
        public final static Property Singnum = new Property(21, int.class, "singnum", false, "SINGNUM");
        public final static Property Muchnum = new Property(22, int.class, "muchnum", false, "MUCHNUM");
        public final static Property Logic = new Property(23, String.class, "logic", false, "LOGIC");
        public final static Property Dzc = new Property(24, String.class, "dzc", false, "DZC");
        public final static Property Hyzk = new Property(25, double.class, "hyzk", false, "HYZK");
        public final static Property Lszk = new Property(26, double.class, "lszk", false, "LSZK");
        public final static Property Cxzk = new Property(27, double.class, "cxzk", false, "CXZK");
        public final static Property Bzts = new Property(28, String.class, "bzts", false, "BZTS");
        public final static Property Hyj = new Property(29, double.class, "hyj", false, "HYJ");
        public final static Property Hyj1 = new Property(30, double.class, "hyj1", false, "HYJ1");
        public final static Property Hyj2 = new Property(31, double.class, "hyj2", false, "HYJ2");
        public final static Property Hyj3 = new Property(32, double.class, "hyj3", false, "HYJ3");
        public final static Property Minzkl = new Property(33, double.class, "minzkl", false, "MINZKL");
        public final static Property Usejf = new Property(34, String.class, "usejf", false, "USEJF");
        public final static Property Usezk = new Property(35, String.class, "usezk", false, "USEZK");
        public final static Property Plu = new Property(36, String.class, "plu", false, "PLU");
        public final static Property ColorCodeShow = new Property(37, String.class, "colorCodeShow", false, "COLOR_CODE_SHOW");
    }


    public GoodsDtoDao(DaoConfig config) {
        super(config);
    }
    
    public GoodsDtoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GOODS_DTO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SID\" TEXT," + // 1: Sid
                "\"UID\" TEXT," + // 2: UId
                "\"CATEGORY_SID\" TEXT," + // 3: category_sid
                "\"COLOR_CODE\" TEXT," + // 4: colorCode
                "\"GROUP_SID\" TEXT," + // 5: group_sid
                "\"IMAGE\" TEXT," + // 6: image
                "\"NAME\" TEXT," + // 7: name
                "\"PRICE\" REAL NOT NULL ," + // 8: price
                "\"COST_PRICE\" REAL NOT NULL ," + // 9: CostPrice
                "\"UNIT\" TEXT," + // 10: unit
                "\"MAIN_PRINTER_SID\" TEXT," + // 11: mainPrinterSid
                "\"BACK_PRINTER_SID\" TEXT," + // 12: backPrinterSid
                "\"CODE\" TEXT," + // 13: Code
                "\"CREATE_TIME\" TEXT," + // 14: createTime
                "\"ORDER_BY\" INTEGER NOT NULL ," + // 15: orderBy
                "\"IS_HIDE\" INTEGER NOT NULL ," + // 16: isHide
                "\"PRO_PRICE\" REAL NOT NULL ," + // 17: proPrice
                "\"PRO_TYPE\" TEXT," + // 18: proType
                "\"PRO_DISCOUT\" REAL NOT NULL ," + // 19: proDiscout
                "\"OLD_PRICE\" REAL NOT NULL ," + // 20: oldPrice
                "\"SINGNUM\" INTEGER NOT NULL ," + // 21: singnum
                "\"MUCHNUM\" INTEGER NOT NULL ," + // 22: muchnum
                "\"LOGIC\" TEXT," + // 23: logic
                "\"DZC\" TEXT," + // 24: dzc
                "\"HYZK\" REAL NOT NULL ," + // 25: hyzk
                "\"LSZK\" REAL NOT NULL ," + // 26: lszk
                "\"CXZK\" REAL NOT NULL ," + // 27: cxzk
                "\"BZTS\" TEXT," + // 28: bzts
                "\"HYJ\" REAL NOT NULL ," + // 29: hyj
                "\"HYJ1\" REAL NOT NULL ," + // 30: hyj1
                "\"HYJ2\" REAL NOT NULL ," + // 31: hyj2
                "\"HYJ3\" REAL NOT NULL ," + // 32: hyj3
                "\"MINZKL\" REAL NOT NULL ," + // 33: minzkl
                "\"USEJF\" TEXT," + // 34: usejf
                "\"USEZK\" TEXT," + // 35: usezk
                "\"PLU\" TEXT," + // 36: plu
                "\"COLOR_CODE_SHOW\" TEXT);"); // 37: colorCodeShow
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GOODS_DTO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GoodsDto entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Sid = entity.getSid();
        if (Sid != null) {
            stmt.bindString(2, Sid);
        }
 
        String UId = entity.getUId();
        if (UId != null) {
            stmt.bindString(3, UId);
        }
 
        String category_sid = entity.getCategory_sid();
        if (category_sid != null) {
            stmt.bindString(4, category_sid);
        }
 
        String colorCode = entity.getColorCode();
        if (colorCode != null) {
            stmt.bindString(5, colorCode);
        }
 
        String group_sid = entity.getGroup_sid();
        if (group_sid != null) {
            stmt.bindString(6, group_sid);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(7, image);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(8, name);
        }
        stmt.bindDouble(9, entity.getPrice());
        stmt.bindDouble(10, entity.getCostPrice());
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(11, unit);
        }
 
        String mainPrinterSid = entity.getMainPrinterSid();
        if (mainPrinterSid != null) {
            stmt.bindString(12, mainPrinterSid);
        }
 
        String backPrinterSid = entity.getBackPrinterSid();
        if (backPrinterSid != null) {
            stmt.bindString(13, backPrinterSid);
        }
 
        String Code = entity.getCode();
        if (Code != null) {
            stmt.bindString(14, Code);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(15, createTime);
        }
        stmt.bindLong(16, entity.getOrderBy());
        stmt.bindLong(17, entity.getIsHide() ? 1L: 0L);
        stmt.bindDouble(18, entity.getProPrice());
 
        String proType = entity.getProType();
        if (proType != null) {
            stmt.bindString(19, proType);
        }
        stmt.bindDouble(20, entity.getProDiscout());
        stmt.bindDouble(21, entity.getOldPrice());
        stmt.bindLong(22, entity.getSingnum());
        stmt.bindLong(23, entity.getMuchnum());
 
        String logic = entity.getLogic();
        if (logic != null) {
            stmt.bindString(24, logic);
        }
 
        String dzc = entity.getDzc();
        if (dzc != null) {
            stmt.bindString(25, dzc);
        }
        stmt.bindDouble(26, entity.getHyzk());
        stmt.bindDouble(27, entity.getLszk());
        stmt.bindDouble(28, entity.getCxzk());
 
        String bzts = entity.getBzts();
        if (bzts != null) {
            stmt.bindString(29, bzts);
        }
        stmt.bindDouble(30, entity.getHyj());
        stmt.bindDouble(31, entity.getHyj1());
        stmt.bindDouble(32, entity.getHyj2());
        stmt.bindDouble(33, entity.getHyj3());
        stmt.bindDouble(34, entity.getMinzkl());
 
        String usejf = entity.getUsejf();
        if (usejf != null) {
            stmt.bindString(35, usejf);
        }
 
        String usezk = entity.getUsezk();
        if (usezk != null) {
            stmt.bindString(36, usezk);
        }
 
        String plu = entity.getPlu();
        if (plu != null) {
            stmt.bindString(37, plu);
        }
 
        String colorCodeShow = entity.getColorCodeShow();
        if (colorCodeShow != null) {
            stmt.bindString(38, colorCodeShow);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GoodsDto entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Sid = entity.getSid();
        if (Sid != null) {
            stmt.bindString(2, Sid);
        }
 
        String UId = entity.getUId();
        if (UId != null) {
            stmt.bindString(3, UId);
        }
 
        String category_sid = entity.getCategory_sid();
        if (category_sid != null) {
            stmt.bindString(4, category_sid);
        }
 
        String colorCode = entity.getColorCode();
        if (colorCode != null) {
            stmt.bindString(5, colorCode);
        }
 
        String group_sid = entity.getGroup_sid();
        if (group_sid != null) {
            stmt.bindString(6, group_sid);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(7, image);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(8, name);
        }
        stmt.bindDouble(9, entity.getPrice());
        stmt.bindDouble(10, entity.getCostPrice());
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(11, unit);
        }
 
        String mainPrinterSid = entity.getMainPrinterSid();
        if (mainPrinterSid != null) {
            stmt.bindString(12, mainPrinterSid);
        }
 
        String backPrinterSid = entity.getBackPrinterSid();
        if (backPrinterSid != null) {
            stmt.bindString(13, backPrinterSid);
        }
 
        String Code = entity.getCode();
        if (Code != null) {
            stmt.bindString(14, Code);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(15, createTime);
        }
        stmt.bindLong(16, entity.getOrderBy());
        stmt.bindLong(17, entity.getIsHide() ? 1L: 0L);
        stmt.bindDouble(18, entity.getProPrice());
 
        String proType = entity.getProType();
        if (proType != null) {
            stmt.bindString(19, proType);
        }
        stmt.bindDouble(20, entity.getProDiscout());
        stmt.bindDouble(21, entity.getOldPrice());
        stmt.bindLong(22, entity.getSingnum());
        stmt.bindLong(23, entity.getMuchnum());
 
        String logic = entity.getLogic();
        if (logic != null) {
            stmt.bindString(24, logic);
        }
 
        String dzc = entity.getDzc();
        if (dzc != null) {
            stmt.bindString(25, dzc);
        }
        stmt.bindDouble(26, entity.getHyzk());
        stmt.bindDouble(27, entity.getLszk());
        stmt.bindDouble(28, entity.getCxzk());
 
        String bzts = entity.getBzts();
        if (bzts != null) {
            stmt.bindString(29, bzts);
        }
        stmt.bindDouble(30, entity.getHyj());
        stmt.bindDouble(31, entity.getHyj1());
        stmt.bindDouble(32, entity.getHyj2());
        stmt.bindDouble(33, entity.getHyj3());
        stmt.bindDouble(34, entity.getMinzkl());
 
        String usejf = entity.getUsejf();
        if (usejf != null) {
            stmt.bindString(35, usejf);
        }
 
        String usezk = entity.getUsezk();
        if (usezk != null) {
            stmt.bindString(36, usezk);
        }
 
        String plu = entity.getPlu();
        if (plu != null) {
            stmt.bindString(37, plu);
        }
 
        String colorCodeShow = entity.getColorCodeShow();
        if (colorCodeShow != null) {
            stmt.bindString(38, colorCodeShow);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GoodsDto readEntity(Cursor cursor, int offset) {
        GoodsDto entity = new GoodsDto( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Sid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // UId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // category_sid
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // colorCode
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // group_sid
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // image
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // name
            cursor.getDouble(offset + 8), // price
            cursor.getDouble(offset + 9), // CostPrice
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // unit
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // mainPrinterSid
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // backPrinterSid
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // Code
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // createTime
            cursor.getInt(offset + 15), // orderBy
            cursor.getShort(offset + 16) != 0, // isHide
            cursor.getDouble(offset + 17), // proPrice
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // proType
            cursor.getDouble(offset + 19), // proDiscout
            cursor.getDouble(offset + 20), // oldPrice
            cursor.getInt(offset + 21), // singnum
            cursor.getInt(offset + 22), // muchnum
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // logic
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // dzc
            cursor.getDouble(offset + 25), // hyzk
            cursor.getDouble(offset + 26), // lszk
            cursor.getDouble(offset + 27), // cxzk
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // bzts
            cursor.getDouble(offset + 29), // hyj
            cursor.getDouble(offset + 30), // hyj1
            cursor.getDouble(offset + 31), // hyj2
            cursor.getDouble(offset + 32), // hyj3
            cursor.getDouble(offset + 33), // minzkl
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // usejf
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // usezk
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // plu
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37) // colorCodeShow
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GoodsDto entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCategory_sid(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setColorCode(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setGroup_sid(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setImage(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPrice(cursor.getDouble(offset + 8));
        entity.setCostPrice(cursor.getDouble(offset + 9));
        entity.setUnit(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setMainPrinterSid(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setBackPrinterSid(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setCode(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setCreateTime(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setOrderBy(cursor.getInt(offset + 15));
        entity.setIsHide(cursor.getShort(offset + 16) != 0);
        entity.setProPrice(cursor.getDouble(offset + 17));
        entity.setProType(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setProDiscout(cursor.getDouble(offset + 19));
        entity.setOldPrice(cursor.getDouble(offset + 20));
        entity.setSingnum(cursor.getInt(offset + 21));
        entity.setMuchnum(cursor.getInt(offset + 22));
        entity.setLogic(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setDzc(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setHyzk(cursor.getDouble(offset + 25));
        entity.setLszk(cursor.getDouble(offset + 26));
        entity.setCxzk(cursor.getDouble(offset + 27));
        entity.setBzts(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setHyj(cursor.getDouble(offset + 29));
        entity.setHyj1(cursor.getDouble(offset + 30));
        entity.setHyj2(cursor.getDouble(offset + 31));
        entity.setHyj3(cursor.getDouble(offset + 32));
        entity.setMinzkl(cursor.getDouble(offset + 33));
        entity.setUsejf(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setUsezk(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setPlu(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setColorCodeShow(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GoodsDto entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GoodsDto entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GoodsDto entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
