/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_lotuscard_LotusCardDriver */

#ifndef _Included_cc_lotuscard_LotusCardDriver
#define _Included_cc_lotuscard_LotusCardDriver
#ifdef __cplusplus
extern "C" {
#endif
#undef cc_lotuscard_LotusCardDriver_RT_ALL
#define cc_lotuscard_LotusCardDriver_RT_ALL 82L
#undef cc_lotuscard_LotusCardDriver_RT_NOT_HALT
#define cc_lotuscard_LotusCardDriver_RT_NOT_HALT 38L
#undef cc_lotuscard_LotusCardDriver_AM_A
#define cc_lotuscard_LotusCardDriver_AM_A 96L
#undef cc_lotuscard_LotusCardDriver_AM_B
#define cc_lotuscard_LotusCardDriver_AM_B 97L
/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    OpenDevice
 * Signature: (Ljava/lang/String;IIIIZ)J
 */
JNIEXPORT jlong JNICALL Java_cc_lotuscard_LotusCardDriver_OpenDevice
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jboolean);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    CloseDevice
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cc_lotuscard_LotusCardDriver_CloseDevice
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    Request
 * Signature: (JILcc/lotuscard/LotusCardParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_Request
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    Anticoll
 * Signature: (JLcc/lotuscard/LotusCardParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_Anticoll
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    Select
 * Signature: (JLcc/lotuscard/LotusCardParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_Select
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    Authentication
 * Signature: (JIILcc/lotuscard/LotusCardParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_Authentication
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    Halt
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_Halt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    Read
 * Signature: (JILcc/lotuscard/LotusCardParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_Read
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    Write
 * Signature: (JILcc/lotuscard/LotusCardParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_Write
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    Increment
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_Increment
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    Decreament
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_Decreament
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    Restore
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_Restore
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    Transfer
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_Transfer
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    LoadKey
 * Signature: (JIILcc/lotuscard/LotusCardParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_LoadKey
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    Beep
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_Beep
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    SendCpuCommand
 * Signature: (JILcc/lotuscard/LotusCardParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_SendCpuCommand
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    GetCardNo
 * Signature: (JILcc/lotuscard/LotusCardParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_GetCardNo
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    GetCardNoEx
 * Signature: (JIBBBLcc/lotuscard/LotusCardParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_GetCardNoEx
  (JNIEnv *, jobject, jlong, jint, jbyte, jbyte, jbyte, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    InitValue
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_InitValue
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    ChangePassword
 * Signature: (JILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_ChangePassword
  (JNIEnv *, jobject, jlong, jint, jstring, jstring);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    ResetCpuCard
 * Signature: (JLcc/lotuscard/LotusCardParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_ResetCpuCard
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    ResetCpuCardNoGetCardNo
 * Signature: (JLcc/lotuscard/LotusCardParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_ResetCpuCardNoGetCardNo
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    DeselectCpuCard
 * Signature: (JLcc/lotuscard/LotusCardParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_DeselectCpuCard
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    SendCOSCommand
 * Signature: (JLcc/lotuscard/LotusCardParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_SendCOSCommand
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    GetBankCardNo
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cc_lotuscard_LotusCardDriver_GetBankCardNo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    ReadData
 * Signature: (JIIBBBLcc/lotuscard/LotusCardParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_ReadData
  (JNIEnv *, jobject, jlong, jint, jint, jbyte, jbyte, jbyte, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    WriteData
 * Signature: (JIBBLcc/lotuscard/LotusCardParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_WriteData
  (JNIEnv *, jobject, jlong, jint, jbyte, jbyte, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    ReadText
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cc_lotuscard_LotusCardDriver_ReadText
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    WriteText
 * Signature: (JILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_WriteText
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    ConnectTest
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_ConnectTest
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    GetErrorCode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cc_lotuscard_LotusCardDriver_GetErrorCode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    GetTwoIdErrorCode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cc_lotuscard_LotusCardDriver_GetTwoIdErrorCode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    GetErrorInfo
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cc_lotuscard_LotusCardDriver_GetErrorInfo
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    GetTwoIdErrorInfo
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cc_lotuscard_LotusCardDriver_GetTwoIdErrorInfo
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    SetCardType
 * Signature: (JC)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_SetCardType
  (JNIEnv *, jobject, jlong, jchar);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    FelicaPolling
 * Signature: (JILcc/lotuscard/LotusCardParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_FelicaPolling
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    ReadNfcBuffer
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cc_lotuscard_LotusCardDriver_ReadNfcBuffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    WriteNfcBuffer
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_WriteNfcBuffer
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    RequestB
 * Signature: (JILcc/lotuscard/LotusCardParam;)I
 */
JNIEXPORT jint JNICALL Java_cc_lotuscard_LotusCardDriver_RequestB
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    SelectB
 * Signature: (JLcc/lotuscard/LotusCardParam;)I
 */
JNIEXPORT jint JNICALL Java_cc_lotuscard_LotusCardDriver_SelectB
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    HaltB
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cc_lotuscard_LotusCardDriver_HaltB
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    GetDeviceNo
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cc_lotuscard_LotusCardDriver_GetDeviceNo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    GetTwoGenerationIDCardNo
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cc_lotuscard_LotusCardDriver_GetTwoGenerationIDCardNo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    SetRfOnOff
 * Signature: (JB)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_SetRfOnOff
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    GetTwoIdInfo
 * Signature: (JLcc/lotuscard/TwoIdInfoParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_GetTwoIdInfo
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    GetTwoIdInfoByServer
 * Signature: (JLjava/lang/String;Lcc/lotuscard/TwoIdInfoParam;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_GetTwoIdInfoByServer
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    GetIdRandom
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_cc_lotuscard_LotusCardDriver_GetIdRandom
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    SaveLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cc_lotuscard_LotusCardDriver_SaveLog
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    GetUsbDeviceCount
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cc_lotuscard_LotusCardDriver_GetUsbDeviceCount
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    GetMcuConfig
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_GetMcuConfig
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    GetIspOption
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_GetIspOption
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    SetIspOption
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_SetIspOption
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    NtagGetVersion
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_NtagGetVersion
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     cc_lotuscard_LotusCardDriver
 * Method:    NtagPwdAuth
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_lotuscard_LotusCardDriver_NtagPwdAuth
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
